sudo: false
language: php
php:
  - nightly
  - 7.0
  - 5.6

matrix:
  allow_failures:
    - php: nightly

install:
  - composer self-update && composer --version
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - composer global require squizlabs/php_codesniffer

script:
  - phpcs --standard=ruleset.xml --extensions=php -n -s .
